#!/bin/sh -eu

. settings.sh
. map_functions.sh

######################################################################

mkdir -p -- "$fig_dir"

while read name geom title; do
  [ -n "${name%#*}" ] || continue

  echo "$name $geom $title"

  l="$lab_dir/$name.vmap"
  f="$fig_dir/$name.fig"

  nom="$(geom2nom $geom 100000)";
  src=''; need_update=''
  for n in $nom; do
    s=$vmap_dir/$n.vmap
    [ -f "$s" ] || continue
    src="$src $s";
    [ -f "$f" -a "$s" -ot "$f" ] || need_update=1
  done

  [ -n "$need_update" ] || continue


  if [ ! -f "$l" ]; then
    vmap_copy -v $src -o "$l" --skip_all --split_labels
  fi

  brd=''
  if [ -f "$f" ]; then
    brd="--keep_border"
  else
    mapsoft_geofig create --datum pulkovo --geom tmerc --geom "$geom"\
                          --rscale 50000 -o "$f"
    brd="--set_brd_from_range"
  fi

  vmap_copy -v $src --out tmp.vmap\
    --range_datum pulk --range_proj tmerc --range "$geom"\
    --range_action crop_spl
  time vmap_copy tmp.vmap --skip_labels "$l"\
    -o "$f" --range_datum pulk --range_proj tmerc --range "$geom"\
    --join_objects 1e-4 $brd
  rm -f tmp.vmap
done < maps.txt
