#!/bin/sh -eu

. settings.sh

mkmap(){
  f="$1"
  base=$(basename $f .fig)
  l="$lab_dir/$base.vmap"

  if [ "$f" -nt "$l" ]; then
    echo "saving labels: $base"
    vmap_copy "$f" -o tmp.vmap --skip_all --split_labels
    vmap_fix_diff "$l" tmp.vmap "$l"
    rm -f tmp.vmap
  fi

  if [ "$f" -nt "$map_dir/$base/$base.100.png" ]; then
    cd $fig_dir
    ../map_install "$base"
    cd -
  fi
}

if [ "$#" = 0 ]; then
  for f in $fig_dir/*.fig; do
    mkmap "$f"
  done
else
  for f in "$@"; do
    echo ">> $f"
    mkmap "$fig_dir/$f.fig"
  done
fi
